/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: 68b261b83542a0b4eeae23754eb37630)
interface __BaseEnv_Env {
	DB: D1Database;
	AWS_REGION: "ap-northeast-1";
	AWS_S3_BUCKET: "reshi-diary-files";
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	GITHUB_TOKEN: string;
	RESEND_API_KEY: string;
	ONEBOT: DurableObjectNamespace /* OneBotSession */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AWS_REGION" | "AWS_S3_BUCKET" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY" | "GITHUB_TOKEN" | "RESEND_API_KEY">> {}
}
