"use client";

import { FormEvent, useEffect, useState } from "react";
import Icon from "../Icon";

type User = { id: string; uid: string; email: string; displayName: string; points: number; isBanned: number; banReason: string | null; bannedAt: number | null; createdAt: number; ticketCount: number };
export default function UserManager() {
  const [users, setUsers] = useState<User[]>([]); const [selected, setSelected] = useState<User | null>(null); const [query, setQuery] = useState(""); const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load(search = "") { const response = await fetch(`/api/admin/users?q=${encodeURIComponent(search)}`, { cache: "no-store" }); const result = await response.json() as { users?: User[]; error?: string }; if (!response.ok) throw new Error(result.error || "用户加载失败"); setUsers(result.users || []); }
  useEffect(() => { const timer = window.setTimeout(() => void load().catch((error) => setMessage(error instanceof Error ? error.message : "用户加载失败")), 0); return () => window.clearTimeout(timer); }, []);
  async function search(event: FormEvent) { event.preventDefault(); setMessage(""); await load(query).catch((error) => setMessage(error instanceof Error ? error.message : "搜索失败")); }
  async function toggleBan() { if (!selected) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/admin/users/${selected.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ banned: !selected.isBanned, reason }) }); const result = await response.json() as { user?: User; error?: string }; if (!response.ok || !result.user) throw new Error(result.error || "操作失败"); const updated = { ...selected, ...result.user }; setSelected(updated); setUsers((items) => items.map((item) => item.id === updated.id ? updated : item)); setMessage(updated.isBanned ? "用户已封禁，现有登录会话已失效" : "用户已解除封禁"); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } finally { setBusy(false); } }
  return <section className="admin-user-manager"><header><div><p>USERS / 用户管理</p><h2>注册用户</h2><span>搜索资料、查看工单风险并管理账户状态</span></div><Icon name="user" /></header><form className="admin-user-search" onSubmit={search}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索 UID、昵称或邮箱" /><button type="submit">搜索</button></form><div className="admin-user-layout"><div className="admin-user-list">{users.map((user) => <button type="button" className={selected?.id === user.id ? "is-active" : ""} key={user.id} onClick={() => { setSelected(user); setReason(user.banReason || ""); }}><span className={user.isBanned ? "is-banned" : ""}>{user.isBanned ? "已封禁" : "正常"}</span><b>{user.displayName}</b><small>UID {user.uid} · {user.ticketCount} 个工单</small></button>)}</div>{selected ? <aside className="admin-user-detail"><div className="admin-user-identity"><span>{selected.displayName.slice(0, 1).toUpperCase()}</span><div><h3>{selected.displayName}</h3><p>UID {selected.uid}</p></div></div><dl><div><dt>邮箱</dt><dd>{selected.email}</dd></div><div><dt>积分</dt><dd>{selected.points}</dd></div><div><dt>工单</dt><dd>{selected.ticketCount}</dd></div><div><dt>注册时间</dt><dd>{new Date(selected.createdAt).toLocaleDateString("zh-CN")}</dd></div></dl>{!selected.isBanned && <label><span>封禁原因（选填）</span><textarea maxLength={200} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="例如：多次恶意提交无效工单" /></label>}<button className={selected.isBanned ? "button-unban" : "button-ban"} type="button" disabled={busy} onClick={toggleBan}>{busy ? "处理中…" : selected.isBanned ? "解除封禁" : "封禁用户"}</button></aside> : <aside className="admin-user-empty">选择一位用户查看详情。</aside>}</div>{message && <p className="notification-message" role="status">{message}</p>}</section>;
}
